### PR TITLE
Add docs on first generation of cases - Jira only

### PR DESCRIPTION
**Pull request by misterpantz**
#### Description

We're adding cases! This adds the docs for the very first rendition of cases in Mondoo. 

This is for Jira only.

As we expand this feature I will move it to a more important spot within the organization of the docs. But for now, for this first release, I'm just replacing the Jira issues topic with a cases topic. 

#### Related issue

n/a

#### Types of changes

- [ ] Functional documentation bug fix (i.e., broken link or some other busted behavior)
- [ ] New functional doc capabilities (i.e., filter search results)
- [x] New content
- [x] Revision to existing content
- [ ] Chore (non-breaking change that does not add functionality or fix an issue)

#### Checklist

- [x] I have read the **README** document about contributing to this repo.
- [x] I have tested my changes locally and there are no issues.
- [x] All commits are signed.

### CODE REVIEW

**Comment by charlesjohnson** [comment]
This looks really good. My only question is, should it be at `/docs/platform/maintain/jira/`?

**Comment by charlesjohnson** [comment]
Also, Chippewah Lander made me laugh. :)

**Review by charlesjohnson — APPROVED** [review]

**Comment by misterpantz** [comment]
> This looks really good. My only question is, should it be at `/docs/platform/maintain/jira/`?

I'm going to move it with the next slice!

**Comment by misterpantz** [comment]
> Also, Chippewah Lander made me laugh. :)

Less text to smoke-and-mirror for screenshots!

**Comment by misterpantz** [comment]
> Also, Chippewah Lander made me laugh. :)

The current location is the path to the old Jira docs -- so this meant no redirects yet!

**Pull request merged**
